---
- src: git@github.com:zakharovnpa/filebeat_roles.git
  scm: git
  version: "v1.0.0"
  name: elasticsearch_roles
- src: git@github.com:zakharovnpa/kibana_roles.git
  scm: git
  version: "v1.0.1"
  name: kibana_roles
- src: git@github.com:zakharovnpa/filebeat_roles.git
  scm: git
  version: "v1.0.0"
  name: filebeat_roles
